In [55]:
import numpy as np
import pandas as pd

In [56]:
df = pd.read_csv(r"C:\Users\akhil\Downloads\dataset.csv")

In [57]:
df

,user_id,session_id,profession,tool,use_case,iterations,prompt_complexity,quality_with_ai,quality_without_ai,productivity_gain,...,overreliance_score,learning_loss,hallucination_flag,failure_type,ease_of_use,ui_complexity,requires_login,subscription_type,session_length,deadline_pressure
0,43140,3817,Software Developer,ChatGPT,Blog Writing,5,low,10.0,4.139299,58.61,...,8.38,1,0,none,9,low,1,freemium,13,low
1,9263,89304,Architect,Perplexity AI,Medical Notes,4,medium,8.0,6.379619,16.20,...,7.27,0,0,none,5,medium,1,paid,6,medium
2,33655,113595,HR Manager,Grammarly AI,Image Generation,6,low,9.0,6.240725,27.59,...,5.14,0,0,none,7,medium,0,paid,56,medium
3,11705,155151,Accountant,Claude,Marketing Copy,3,medium,7.5,6.113465,13.87,...,7.73,0,0,none,10,low,1,free,44,high
4,4384,4358,Scientist,Gemini,Marketing Copy,2,medium,7.0,5.221701,17.78,...,3.65,0,0,none,7,medium,0,freemium,36,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,17144,22133,Student,Cursor AI,Resume Building,4,high,8.0,6.322623,16.77,...,8.03,0,1,incomplete,8,medium,0,free,39,high
4996,49443,64573,Professor,Cursor AI,Research Summary,2,high,7.0,3.860208,31.40,...,7.85,1,0,none,6,low,0,free,9,low
4997,3097,198064,Mechanical Engineer,Midjourney,Marketing Copy,1,high,6.5,4.667756,18.32,...,8.50,0,0,none,9,low,0,free,17,high
4998,42128,170752,HR Manager,DALL-E,Resume Building,3,medium,7.5,5.447681,20.52,...,6.68,0,0,none,5,medium,1,free,34,low
4999,4210,181799,YouTuber,AutoGPT,Code Generation,1,medium,6.5,5.948105,5.52,...,8.87,0,0,none,6,medium,1,freemium,16,low

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   user_id                5000 non-null   int64
 1   session_id             5000 non-null   int64
 2   profession             5000 non-null   object
 3   tool                   5000 non-null   object
 4   use_case               5000 non-null   object
 5   iterations             5000 non-null   int64
 6   prompt_complexity      5000 non-null   object
 7   quality_with_ai        5000 non-null   float64
 8   quality_without_ai     5000 non-null   float64
 9   productivity_gain      5000 non-null   float64
 10  final_quality_label    5000 non-null   object
 11  confidence_with_ai     5000 non-null   int64
 12  confidence_without_ai  5000 non-null   int64
 13  overreliance_score     5000 non-null   float64
 14  learning_loss          5000 non-null   int64
 15  hallucination_flag     5000 non-null   int64
 16  failure_type           5000 non-null   object
 17  ease_of_use            5000 non-null   int64
 18  ui_complexity          5000 non-null   object
 19  requires_login         5000 non-null   int64
 20  subscription_type      5000 non-null   object
 21  session_length         5000 non-null   int64
 22  deadline_pressure      5000 non-null   object
dtypes: float64(4), int64(10), object(9)
memory usage: 898.6+ KB

In [59]:
df.describe()

,user_id,session_id,iterations,quality_with_ai,quality_without_ai,productivity_gain,confidence_with_ai,confidence_without_ai,overreliance_score,learning_loss,hallucination_flag,ease_of_use,requires_login,session_length
count,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.0000,5000.000000,5000.00000
mean,24790.77600,101821.548800,3.522200,7.845500,4.990965,28.545364,7.336000,4.506600,5.992730,0.50040,0.294200,7.5296,0.496600,32.62220
std,14401.10469,58055.889587,1.728035,0.945811,1.147355,14.869652,1.137437,1.456565,1.744494,0.50005,0.455728,1.7093,0.500038,16.42886
min,28.00000,41.000000,1.000000,6.500000,3.002290,-4.940000,5.000000,1.000000,3.000000,0.00000,0.000000,5.0000,0.000000,5.00000
25%,12495.75000,52281.250000,2.000000,7.000000,4.010486,17.840000,6.750000,3.000000,4.477500,0.00000,0.000000,6.0000,0.000000,18.00000
50%,24699.50000,102303.000000,4.000000,8.000000,4.964137,28.570000,7.000000,5.000000,5.965000,1.00000,0.000000,8.0000,0.000000,33.00000
75%,37280.00000,153499.750000,5.000000,8.500000,5.990921,39.192500,8.000000,6.000000,7.520000,1.00000,1.000000,9.0000,1.000000,47.00000
max,49997.00000,199928.000000,6.000000,10.000000,6.999554,69.970000,10.000000,8.000000,9.000000,1.00000,1.000000,10.0000,1.000000,60.00000

In [60]:
df.head()

,user_id,session_id,profession,tool,use_case,iterations,prompt_complexity,quality_with_ai,quality_without_ai,productivity_gain,...,overreliance_score,learning_loss,hallucination_flag,failure_type,ease_of_use,ui_complexity,requires_login,subscription_type,session_length,deadline_pressure
0,43140,3817,Software Developer,ChatGPT,Blog Writing,5,low,10.0,4.139299,58.61,...,8.38,1,0,none,9,low,1,freemium,13,low
1,9263,89304,Architect,Perplexity AI,Medical Notes,4,medium,8.0,6.379619,16.20,...,7.27,0,0,none,5,medium,1,paid,6,medium
2,33655,113595,HR Manager,Grammarly AI,Image Generation,6,low,9.0,6.240725,27.59,...,5.14,0,0,none,7,medium,0,paid,56,medium
3,11705,155151,Accountant,Claude,Marketing Copy,3,medium,7.5,6.113465,13.87,...,7.73,0,0,none,10,low,1,free,44,high
4,4384,4358,Scientist,Gemini,Marketing Copy,2,medium,7.0,5.221701,17.78,...,3.65,0,0,none,7,medium,0,freemium,36,medium

In [61]:
df= df.drop(columns=['user_id','session_id'])

In [62]:
num_cols = df.select_dtypes(include=['int','float']).columns
num_cols

Index(['iterations', 'quality_with_ai', 'quality_without_ai',
       'productivity_gain', 'confidence_with_ai', 'confidence_without_ai',
       'overreliance_score', 'learning_loss', 'hallucination_flag',
       'ease_of_use', 'requires_login', 'session_length'],
      dtype='object')

In [63]:
cat_cols = df.select_dtypes(exclude=['int','float']).columns
cat_cols

Index(['profession', 'tool', 'use_case', 'prompt_complexity',
       'final_quality_label', 'failure_type', 'ui_complexity',
       'subscription_type', 'deadline_pressure'],
      dtype='object')

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   profession             5000 non-null   object
 1   tool                   5000 non-null   object
 2   use_case               5000 non-null   object
 3   iterations             5000 non-null   int64
 4   prompt_complexity      5000 non-null   object
 5   quality_with_ai        5000 non-null   float64
 6   quality_without_ai     5000 non-null   float64
 7   productivity_gain      5000 non-null   float64
 8   final_quality_label    5000 non-null   object
 9   confidence_with_ai     5000 non-null   int64
 10  confidence_without_ai  5000 non-null   int64
 11  overreliance_score     5000 non-null   float64
 12  learning_loss          5000 non-null   int64
 13  hallucination_flag     5000 non-null   int64
 14  failure_type           5000 non-null   object
 15  ease_of_use            5000 non-null   int64
 16  ui_complexity          5000 non-null   object
 17  requires_login         5000 non-null   int64
 18  subscription_type      5000 non-null   object
 19  session_length         5000 non-null   int64
 20  deadline_pressure      5000 non-null   object
dtypes: float64(4), int64(8), object(9)
memory usage: 820.4+ KB

In [65]:
for i in num_cols:
    print(i,df[i].nunique())

iterations 6
quality_with_ai 8
quality_without_ai 5000
productivity_gain 3294
confidence_with_ai 6
confidence_without_ai 8
overreliance_score 601
learning_loss 2
hallucination_flag 2
ease_of_use 6
requires_login 2
session_length 56

In [66]:
for i in cat_cols:
    print(i,df[i].nunique())

profession 31
tool 16
use_case 18
prompt_complexity 3
final_quality_label 2
failure_type 4
ui_complexity 3
subscription_type 3
deadline_pressure 3

In [67]:
df = df.drop(columns=['quality_without_ai','profession','tool','use_case','overreliance_score','session_length','failure_type'])

In [68]:
df.describe()

,iterations,quality_with_ai,productivity_gain,confidence_with_ai,confidence_without_ai,learning_loss,hallucination_flag,ease_of_use,requires_login
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.0000,5000.000000
mean,3.522200,7.845500,28.545364,7.336000,4.506600,0.50040,0.294200,7.5296,0.496600
std,1.728035,0.945811,14.869652,1.137437,1.456565,0.50005,0.455728,1.7093,0.500038
min,1.000000,6.500000,-4.940000,5.000000,1.000000,0.00000,0.000000,5.0000,0.000000
25%,2.000000,7.000000,17.840000,6.750000,3.000000,0.00000,0.000000,6.0000,0.000000
50%,4.000000,8.000000,28.570000,7.000000,5.000000,1.00000,0.000000,8.0000,0.000000
75%,5.000000,8.500000,39.192500,8.000000,6.000000,1.00000,1.000000,9.0000,1.000000
max,6.000000,10.000000,69.970000,10.000000,8.000000,1.00000,1.000000,10.0000,1.000000

In [69]:
df.isnull().sum()

iterations               0
prompt_complexity        0
quality_with_ai          0
productivity_gain        0
final_quality_label      0
confidence_with_ai       0
confidence_without_ai    0
learning_loss            0
hallucination_flag       0
ease_of_use              0
ui_complexity            0
requires_login           0
subscription_type        0
deadline_pressure        0
dtype: int64

In [70]:
df.duplicated().sum()

0

In [71]:
x = df.drop(columns=['productivity_gain'])
x

,iterations,prompt_complexity,quality_with_ai,final_quality_label,confidence_with_ai,confidence_without_ai,learning_loss,hallucination_flag,ease_of_use,ui_complexity,requires_login,subscription_type,deadline_pressure
0,5,low,10.0,high,10,4,1,0,9,low,1,freemium,low
1,4,medium,8.0,high,7,5,0,0,5,medium,1,paid,medium
2,6,low,9.0,high,8,7,0,0,7,medium,0,paid,medium
3,3,medium,7.5,medium,7,6,0,0,10,low,1,free,high
4,2,medium,7.0,medium,6,4,0,0,7,medium,0,freemium,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4,high,8.0,high,7,7,0,1,8,medium,0,free,high
4996,2,high,7.0,medium,6,2,1,0,6,low,0,free,low
4997,1,high,6.5,medium,5,4,0,0,9,low,0,free,high
4998,3,medium,7.5,medium,6,5,0,0,5,medium,1,free,low
4999,1,medium,6.5,medium,6,6,0,0,6,medium,1,freemium,low

In [72]:
y = df['productivity_gain']
y

0       58.61
1       16.20
2       27.59
3       13.87
4       17.78
        ...
4995    16.77
4996    31.40
4997    18.32
4998    20.52
4999     5.52
Name: productivity_gain, Length: 5000, dtype: float64

In [73]:
from sklearn.model_selection import train_test_split

In [74]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((4000, 13), (4000,), (1000, 13), (1000,))

In [75]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,MinMaxScaler

In [77]:
x

,iterations,prompt_complexity,quality_with_ai,final_quality_label,confidence_with_ai,confidence_without_ai,learning_loss,hallucination_flag,ease_of_use,ui_complexity,requires_login,subscription_type,deadline_pressure
0,5,low,10.0,high,10,4,1,0,9,low,1,freemium,low
1,4,medium,8.0,high,7,5,0,0,5,medium,1,paid,medium
2,6,low,9.0,high,8,7,0,0,7,medium,0,paid,medium
3,3,medium,7.5,medium,7,6,0,0,10,low,1,free,high
4,2,medium,7.0,medium,6,4,0,0,7,medium,0,freemium,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4,high,8.0,high,7,7,0,1,8,medium,0,free,high
4996,2,high,7.0,medium,6,2,1,0,6,low,0,free,low
4997,1,high,6.5,medium,5,4,0,0,9,low,0,free,high
4998,3,medium,7.5,medium,6,5,0,0,5,medium,1,free,low
4999,1,medium,6.5,medium,6,6,0,0,6,medium,1,freemium,low

In [78]:
for i in x:
    print(i,x[i].unique())

iterations [5 4 6 3 2 1]
prompt_complexity ['low' 'medium' 'high']
quality_with_ai [10.   8.   9.   7.5  7.   6.5  8.5  9.5]
final_quality_label ['high' 'medium']
confidence_with_ai [10  7  8  6  9  5]
confidence_without_ai [4 5 7 6 2 3 8 1]
learning_loss [1 0]
hallucination_flag [0 1]
ease_of_use [ 9  5  7 10  8  6]
ui_complexity ['low' 'medium' 'high']
requires_login [1 0]
subscription_type ['freemium' 'paid' 'free']
deadline_pressure ['low' 'medium' 'high']

In [83]:
# cols_for_ohe
order_for_oe = ['low','medium','high']

ohe= OneHotEncoder()
ohe

oe = OrdinalEncoder(categories=order_for_oe)
oe

min_max = MinMaxScaler()
min_max

MinMaxScaler()

In [81]:
cols_ohe = ['subscription_type']
cols_oe = ['prompt_complexity','final_quality_label','ui_complexity','deadline_pressure']
cols_min_max =['iterations','quality_with_ai','confidence_with_ai','confidence_without_ai','learning_loss','hallucination_flag','ease_of_use','requires_login']

In [84]:
from sklearn.compose import ColumnTransformer

In [93]:
ct1 = ColumnTransformer(transformers=[('ordinal',OrdinalEncoder(),cols_oe),
                                     ('onehot',OneHotEncoder(),cols_ohe),
                                     ('minmax',MinMaxScaler(),cols_min_max)])